name: Deploy Preview

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write # Grant write access to pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          npm install -g vercel
          DEPLOY_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm)
          echo "Vercel deployment URL: $DEPLOY_URL"
          echo "VERCEL_URL=$DEPLOY_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Comment on PR with deployment URL
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployUrl = process.env.VERCEL_URL; 
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview URL: ${deployUrl}`
            });
