name: Deploy Preview

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          npm install -g vercel
          DEPLOY_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm)
          echo "Vercel deployment URL: $DEPLOY_URL"
          echo "VERCEL_URL=$DEPLOY_URL" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Create a comment with deployment link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const deploymentUrl = process.env.VERCEL_URL;
            const comment = `Preview deployment URL: ${deploymentUrl}`;
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
