name: 'Netlify PR Preview Deploy'

on:
  pull_request:
    branches:
      - main # Triggers when a PR is opened against `main`
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: 'Deploy PR Preview to Netlify'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Set NODE_ENV to Development
        run: echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: Build for Preview
        run: npm run build # This will now use NODE_ENV=development

      - name: Deploy to Netlify Preview
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --dir=dist --alias=pr-${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NODE_ENV: development

      - name: Output Preview URL
        run: |
          NEW_URL="https://preview-dipanshu-portfolio-pr-${{ github.event.pull_request.number }}.netlify.app"
          echo "Preview URL: $NEW_URL"
          echo "NEW_URL=$NEW_URL" >> $GITHUB_ENV
